# Generated by Django 5.2.5 on 2025-09-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_unique_together_and_more'),
        ('hostel', '0002_hostelblock_school_alter_hostelblock_name_and_more'),
        ('schools', '0001_initial'),
        ('users', '0008_remove_parent_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('bunk_top', 'Bunk Bed (Top)'), ('bunk_bottom', 'Bunk Bed (Bottom)')], default='single', max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('home', 'Home Visit'), ('medical', 'Medical'), ('emergency', 'Emergency'), ('personal', 'Personal'), ('academic', 'Academic'), ('other', 'Other')], default='home', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='hostelcomplaint',
            options={'ordering': ['-submitted_date']},
        ),
        migrations.RemoveIndex(
            model_name='hostelallocation',
            name='hostel_host_room_id_3dcd2b_idx',
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='room',
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='hostel_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.payment'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='total_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='attachment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('cleanliness', 'Cleanliness'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('internet', 'Internet/WiFi'), ('security', 'Security'), ('noise', 'Noise'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='floor_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostelallocation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('vacated', 'Vacated'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostelallocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocation', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to='users.staffprofile'),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='hostelblock',
            index=models.Index(fields=['school', 'is_active'], name='hostel_host_school__c15c65_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelcomplaint',
            index=models.Index(fields=['category', 'status'], name='hostel_host_categor_e55bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelcomplaint',
            index=models.Index(fields=['assigned_to', 'status'], name='hostel_host_assigne_a73a89_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelroom',
            index=models.Index(fields=['room_type', 'is_available'], name='hostel_host_room_ty_9352ae_idx'),
        ),
        migrations.AddField(
            model_name='hostelbed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelroom'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='hostel.hostelbed'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['bed', 'status'], name='hostel_host_bed_id_f7f574_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['status', 'created_at'], name='hostel_host_status_4ab2ea_idx'),
        ),
        migrations.AddField(
            model_name='hostelleaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='hostelleaverequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leaves', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='hostelleaverequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='hostelbed',
            index=models.Index(fields=['room', 'bed_number'], name='hostel_host_room_id_4a8f65_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelbed',
            index=models.Index(fields=['room', 'is_available'], name='hostel_host_room_id_b65c29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelbed',
            unique_together={('room', 'bed_number')},
        ),
        migrations.AddIndex(
            model_name='hostelleaverequest',
            index=models.Index(fields=['student', 'status'], name='hostel_host_student_5561bb_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelleaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='hostel_host_start_d_747dda_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelleaverequest',
            index=models.Index(fields=['submitted_date', 'status'], name='hostel_host_submitt_3e3d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelleaverequest',
            index=models.Index(fields=['leave_type', 'status'], name='hostel_host_leave_t_efde52_idx'),
        ),
    ]
