# Generated by Django 5.2.6 on 2025-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_hostelbed_hostelleaverequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelblock',
            name='floor_config',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='total_floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='ac_type',
            field=models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], default='non_ac', max_length=10),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='floor_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='room_type',
            field=models.CharField(choices=[('1_bed', '1 Bed'), ('2_beds', '2 Beds'), ('3_beds', '3 Beds'), ('4_beds', '4 Beds'), ('5_beds', '5 Beds'), ('6_beds', '6 Beds'), ('dormitory', 'Dormitory (12 Beds)')], default='2_beds', max_length=15),
        ),
    ]
