# Generated by Django 5.2.5 on 2025-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hostelblock_floor_config_hostelblock_total_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelroom',
            name='annual_fee_ac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='annual_fee_non_ac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
