# Generated by Django 5.2.6 on 2025-09-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_hostelroom_annual_fee_ac_and_more'),
        ('users', '0011_staffprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='users.studentprofile'),
        ),
    ]
