# Generated by Django 5.2.6 on 2025-09-17 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_schooladmissiondecision_enrollment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_student_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='is_payment_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='student_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_decision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='user_id_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schooladmissiondecision',
            name='user_id_allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
