# Generated by Django 5.2.5 on 2025-09-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_add_payment_finalization_and_user_allocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeStructure',
            new_name='AdmissionFeeStructure',
        ),
        migrations.AlterModelTable(
            name='admissionfeestructure',
            table='admissions_admissionfeestructure',
        ),
    ]
