# Generated by Django 5.2.5 on 2025-09-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_rename_feestructure_admissionfeestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='If different from parents', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_relationship',
            field=models.CharField(blank=True, help_text='e.g., Uncle, Aunt, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='primary_contact',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], default='father', help_text='Primary contact for school communications', max_length=20),
        ),
    ]
