# Generated by Django 5.2.5 on 2025-09-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_admissionapplication_father_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionfeestructure',
            name='class_range',
            field=models.CharField(choices=[('ukg', 'UKG/Kindergarten'), ('1-8', 'Class 1-8'), ('9-10', 'Class 9-10'), ('11-12', 'Class 11-12')], max_length=10),
        ),
    ]
