# Generated by Django 5.2.5 on 2025-09-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_alter_admissionfeestructure_class_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionfeestructure',
            name='class_range',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('lkg', 'LKG/Lower Kindergarten'), ('ukg', 'UKG/Upper Kindergarten'), ('1-8', 'Class 1-8'), ('9-10', 'Class 9-10'), ('11-12', 'Class 11-12')], max_length=10),
        ),
    ]
