# Generated by Django 5.2.5 on 2025-09-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_alter_admissionfeestructure_class_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='caste',
            field=models.CharField(blank=True, help_text='Caste (for reservation purposes if applicable)', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact person (if different from parents)', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to student', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='family_type',
            field=models.CharField(blank=True, choices=[('nuclear', 'Nuclear Family'), ('joint', 'Joint Family'), ('single_parent', 'Single Parent'), ('other', 'Other')], help_text='Type of family structure', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhar card number (optional)', max_length=12),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_address',
            field=models.TextField(blank=True, help_text="Father's residential address"),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual income in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_company_name',
            field=models.CharField(blank=True, help_text='Company/Organization name', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_emergency_contact',
            field=models.CharField(blank=True, help_text='Alternative contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_qualification',
            field=models.CharField(blank=True, help_text='Educational qualification', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhar card number (optional)', max_length=12),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_address',
            field=models.TextField(blank=True, help_text="Guardian's residential address"),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual income in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_company_name',
            field=models.CharField(blank=True, help_text='Company/Organization name', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_emergency_contact',
            field=models.CharField(blank=True, help_text='Alternative contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_qualification',
            field=models.CharField(blank=True, help_text='Educational qualification', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhar card number (optional)', max_length=12),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_address',
            field=models.TextField(blank=True, help_text="Mother's residential address"),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual income in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_company_name',
            field=models.CharField(blank=True, help_text='Company/Organization name', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_emergency_contact',
            field=models.CharField(blank=True, help_text='Alternative contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_qualification',
            field=models.CharField(blank=True, help_text='Educational qualification', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_tongue',
            field=models.CharField(blank=True, help_text="Student's mother tongue", max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of children', null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='phone', help_text='Preferred method of communication', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='religion',
            field=models.CharField(blank=True, help_text='Religion (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='total_family_members',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of family members', null=True),
        ),
    ]
