# Generated by Django 5.2.6 on 2025-09-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_unique_together_and_more'),
        ('users', '0011_staffprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='academic_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('hostel', 'Hostel Fee'), ('library', 'Library Fee'), ('lab', 'Lab Fee'), ('exam', 'Exam Fee'), ('admission', 'Admission Fee'), ('other', 'Other Fee')], default='tuition', max_length=20),
        ),
        migrations.AlterField(
            model_name='feeinvoice',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.feestructure'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['fee_type', 'student'], name='fees_feeinv_fee_typ_39091d_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['academic_year', 'student'], name='fees_feeinv_academi_40d268_idx'),
        ),
    ]
