# Generated by Django 5.2.5 on 2025-09-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_admissionapplication_father_email_and_more'),
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='admission_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to='admissions.admissionapplication'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='parentprofile',
            unique_together={('student', 'relationship')},
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['email'], name='users_paren_email_4ac2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['admission_application'], name='users_paren_admissi_8ee189_idx'),
        ),
        migrations.AddField(
            model_name='parentotp',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to='users.parentprofile'),
        ),
        migrations.AddIndex(
            model_name='parentotp',
            index=models.Index(fields=['email', 'is_verified'], name='users_paren_email_7641a6_idx'),
        ),
        migrations.AddIndex(
            model_name='parentotp',
            index=models.Index(fields=['email', 'expires_at'], name='users_paren_email_27cb79_idx'),
        ),
        migrations.AddIndex(
            model_name='parentotp',
            index=models.Index(fields=['parent', 'created_at'], name='users_paren_parent__f73720_idx'),
        ),
    ]
