# Generated by Django 5.2.5 on 2025-09-17 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_parentotp_parentprofile_admission_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.parentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token', 'is_active'], name='users_paren_session_89fcbc_idx'), models.Index(fields=['parent', 'is_active'], name='users_paren_parent__6708fc_idx'), models.Index(fields=['expires_at'], name='users_paren_expires_f4b484_idx')],
            },
        ),
    ]
