# Generated by Django 5.2.5 on 2025-09-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_parentsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentSession',
        ),
    ]
