# Generated by Django 5.2.5 on 2025-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('faculty', 'Faculty'), ('warden', 'Warden'), ('admin', 'Admin'), ('librarian', 'Librarian'), ('management', 'Management')], max_length=20),
        ),
    ]
